name: software-engineering-lab-9

on:
  push:
    branches:
      - master
      - develop
      - jwt-auth

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:17
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and Start Containers
        run: docker-compose up --build -d

      - name: Execute Unit Tests
        run: |
          docker exec $(docker-compose ps -q api) python manage.py test DjangoApp.tests
        # Adjust the path if necessary

  docs:
    needs: test  # Ensures that tests pass before running docs
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Generate API documentation
        run: |
          source venv/bin/activate
          python manage.py generateschema > docs.json

      - name: Commit and push documentation
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git diff --quiet || (
            git add docs.json index.html
            git commit -m "Updated documentation"
            git push origin HEAD
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
